language: node_js

node_js:
    - "4"
    - "6"

sudo: false

after_success:
    - if [ "$TRAVIS_NODE_VERSION" == "6" ]; then npm install https://github.com/alekitto/ocular.js.git; fi
    - if [ "$TRAVIS_NODE_VERSION" == "6" ]; then $(npm bin)/ocular coverage/clover.xml; fi
